name: Manual - Fetch NFL Weather

on:
  workflow_dispatch: 

jobs:
  update-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests firebase-admin
        
      - name: Execute Python Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python scripts/fetch_weather.py
