# Master mapping of NFL Teams to their default Home Stadium Name
# This must match the keys in your stadiums.json exactly.
TEAM_DEFAULT_STADIUMS = {
    "Buffalo Bills": "Highmark Stadium",
    "Miami Dolphins": "Hard Rock Stadium",
    "New England Patriots": "Gillette Stadium",
    "New York Jets": "MetLife Stadium",
    "Dallas Cowboys": "AT&T Stadium",
    "New York Giants": "MetLife Stadium",
    "Philadelphia Eagles": "Lincoln Financial Field",
    "Washington Commanders": "Commanders Field",
    "Baltimore Ravens": "M&T Bank Stadium",
    "Cincinnati Bengals": "Paycor Stadium",
    "Cleveland Browns": "Cleveland Browns Stadium",
    "Pittsburgh Steelers": "Acrisure Stadium",
    "Chicago Bears": "Soldier Field",
    "Detroit Lions": "Ford Field",
    "Green Bay Packers": "Lambeau Field",
    "Minnesota Vikings": "U.S. Bank Stadium",
    "Houston Texans": "NRG Stadium",
    "Indianapolis Colts": "Lucas Oil Stadium",
    "Jacksonville Jaguars": "EverBank Stadium",
    "Tennessee Titans": "Nissan Stadium",
    "Atlanta Falcons": "Mercedes-Benz Stadium",
    "Carolina Panthers": "Bank of America Stadium",
    "New Orleans Saints": "Caesars Superdome",
    "Tampa Bay Buccaneers": "Raymond James Stadium",
    "Denver Broncos": "Empower Field at Mile High",
    "Kansas City Chiefs": "Arrowhead Stadium",
    "Las Vegas Raiders": "Allegiant Stadium",
    "Los Angeles Chargers": "SoFi Stadium",
    "Arizona Cardinals": "State Farm Stadium",
    "Los Angeles Rams": "SoFi Stadium",
    "San Francisco 49ers": "Levi's Stadium",
    "Seattle Seahawks": "Lumen Field"
}
